name: MARCOSFRESL FastAPI demo

on:
  push:
    branches:
      - master
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v5

    - name: install dependencies
      run: 
        pip3 install -r requirements.txt

    - name: unittest
      run:
        pytest test/test.py 
    