name: MARCOSFRESL FastAPI demo

on:
  push:
    branches:
      - main
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Upgrade pip and build tools
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Run tests
        run: pytest test/test.py

      - name: docker build
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/marcosfresl-fastapi-demo:${{ github.sha }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: docker push
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/marcosfresl-fastapi-demo:${{ github.sha }}

